export const types = {
  GET_APPLICATION: 'GET_APPLICATION',
  REMOVE_APPLICATION: 'REMOVE_APPLICATION',
  GET_QUESTIONS: 'GET_QUESTIONS',
  GET_COMMENTS: 'GET_COMMENTS',
  POST_COMMENTS: 'POST_COMMENTS',
}
